const bCrypt = require('bcrypt');
module.exports = {
    up: (queryInterface) => {
        return queryInterface.bulkInsert('bookings', [
            {
                status: 'waiting',
                idRestaurant: 1,
                nameCustomer: "ahihi",
                phone: "123123",
                numberPeople: 4,
                arrivalTime: 11,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                status: 'waiting',
                idRestaurant: 2,
                nameCustomer: "huhuhu",
                phone: "11311311",
                numberPeople: 4,
                arrivalTime: 11400,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 4,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                status: 'waiting',
                idRestaurant: 2,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'canceled',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 4,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                status: 'waiting',
                idRestaurant: 2,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 4,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                status: 'waiting',
                idRestaurant: 2,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 4,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 4,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 2,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                status: 'waiting',
                idRestaurant: 1,
                numberPeople: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
        ], {});
    },

    down: (queryInterface) =>
        queryInterface.bulkDelete('restaurants', null, {})

};
