module.exports = {
    up: (queryInterface) => {
        return queryInterface.bulkInsert('products', [
            {
                name: 'Laptop dell',
                descriptions: 'laptop dell HaNoi',
                idCategory: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: 'Laptop Hp',
                descriptions: ' laptop hp max',
                idCategory: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: 'Laptop ASUS',
                descriptions: ' Laptop vip',
                idCategory: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Macbook',
                descriptions: 'Rich Kid',
                idCategory: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Kuuga',
                descriptions: 'First',
                idCategory: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Agito',
                descriptions: 'Second',
                idCategory: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Ryuki',
                descriptions: 'Best dragon knight',
                idCategory: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Faiz',
                descriptions: '555',
                idCategory: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Blade',
                descriptions: 'Tachibana-san',
                idCategory: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Kabuto',
                descriptions: 'God of sun',
                idCategory: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Decade',
                descriptions: 'Decabu',
                idCategory: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Double',
                descriptions: '2 in 1',
                idCategory: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'OOO',
                descriptions: 'Poor',
                idCategory: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Ex-aid',
                descriptions: 'Clear game no continue',
                idCategory: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Build',
                descriptions: 'Physical',
                idCategory: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Zio',
                descriptions: 'king of time',
                idCategory: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Zero-one',
                descriptions: 'Izu',
                idCategory: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Blades',
                descriptions: 'vantho',
                idCategory: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: 'Revice',
                descriptions: 'Double version2',
                idCategory: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
        ], {});
    },

    down: (queryInterface) =>
        queryInterface.bulkDelete('users', null, {})

};
