const bCrypt = require('bcrypt');
module.exports = {
    up: (queryInterface) => {
        return queryInterface.bulkInsert('tables', [
            {
                name: '1-1',
                status: 'booked',
                numberSeat: 1,
                idRestaurant: 1,
                nameCustomer: "ahihi",
                phone: "123123",
                arrivalTime: 16000,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-2',
                status: 'booked',
                numberSeat: 2,
                idRestaurant: 1,
                nameCustomer: "huhuhu",
                phone: "69369369",
                arrivalTime: 16400,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '1-3',
                status: 'ready',
                numberSeat: 4,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '1-4',
                status: 'ready',
                numberSeat: 10,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-5',
                status: 'used',
                numberSeat: 6,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-6',
                status: 'ready',
                numberSeat: 2,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '1-7',
                status: 'ready',
                numberSeat: 8,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '1-8',
                status: 'used',
                numberSeat: 10,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '1-9',
                status: 'ready',
                numberSeat: 4,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-10',
                status: 'ready',
                numberSeat: 2,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '1-11',
                status: 'ready',
                numberSeat: 4,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '1-12',
                status: 'ready',
                numberSeat: 10,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '1-13',
                status: 'ready',
                numberSeat: 6,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-14',
                status: 'ready',
                numberSeat: 2,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '1-15',
                status: 'ready',
                numberSeat: 4,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '1-16',
                status: 'ready',
                numberSeat: 8,
                idRestaurant: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '2-1',
                status: 'ready',
                numberSeat: 1,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '2-2',
                status: 'ready',
                numberSeat: 4,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '2-3',
                status: 'ready',
                numberSeat: 6,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '2-4',
                status: 'ready',
                numberSeat: 8,
                idRestaurant: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '3-1',
                status: 'ready',
                numberSeat: 2,
                idRestaurant: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '3-2',
                status: 'ready',
                numberSeat: 6,
                idRestaurant: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '3-3',
                status: 'ready',
                numberSeat: 1,
                idRestaurant: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '3-4',
                status: 'ready',
                numberSeat: 8,
                idRestaurant: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            }, {
                name: '4-1',
                status: 'ready',
                numberSeat: 1,
                idRestaurant: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
        ], {});
    },

    down: (queryInterface) =>
        queryInterface.bulkDelete('restaurants', null, {})

};
